# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-28 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atm',
            options={'ordering': ['id']},
        ),
    ]
