# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-28 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20170728_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoConta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('valor', models.FloatField(default=0)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Conta')),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
    ]
